spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost/${MYSQL_DATABASE:ricmed_api}
    username: ${MYSQL_USER:ricmed}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}


