spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost/ricmed_api
    username: ricmed
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never


